// Generated by rstantools.  Do not edit by hand.

/*
    assessEpidemicCurves is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    assessEpidemicCurves is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with assessEpidemicCurves.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_lgp_Rt_homo_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_lgp_Rt_homo");
    reader.add_event(81, 79, "end", "model_lgp_Rt_homo");
    return reader;
}
#include <stan_meta_header.hpp>
class model_lgp_Rt_homo
  : public stan::model::model_base_crtp<model_lgp_Rt_homo> {
private:
        int D_seed;
        int D;
        std::vector<int> y;
        std::vector<double> x;
        vector_d mu;
        int S;
        double mean_omega;
        double sd_omega;
        double alpha;
        double ell;
        double nugget;
        int c;
        vector_d y_reg;
        matrix_d C;
        matrix_d L;
        double a;
        double b;
        vector_d omega;
        vector_d log_omega;
public:
    model_lgp_Rt_homo(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_lgp_Rt_homo(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_lgp_Rt_homo_namespace::model_lgp_Rt_homo";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "D_seed", "int", context__.to_vec());
            D_seed = int(0);
            vals_i__ = context__.vals_i("D_seed");
            pos__ = 0;
            D_seed = vals_i__[pos__++];
            check_greater_or_equal(function__, "D_seed", D_seed, 1);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "D", "int", context__.to_vec());
            D = int(0);
            vals_i__ = context__.vals_i("D");
            pos__ = 0;
            D = vals_i__[pos__++];
            check_greater_or_equal(function__, "D", D, 2);
            current_statement_begin__ = 8;
            validate_non_negative_index("y", "D", D);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(D));
            y = std::vector<int>(D, int(0));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_k_0_max__ = D;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                y[k_0__] = vals_i__[pos__++];
            }
            size_t y_i_0_max__ = D;
            for (size_t i_0__ = 0; i_0__ < y_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y[i_0__]", y[i_0__], 0);
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("x", "D", D);
            context__.validate_dims("data initialization", "x", "double", context__.to_vec(D));
            x = std::vector<double>(D, double(0));
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_k_0_max__ = D;
            for (size_t k_0__ = 0; k_0__ < x_k_0_max__; ++k_0__) {
                x[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 10;
            validate_non_negative_index("mu", "D", D);
            context__.validate_dims("data initialization", "mu", "vector_d", context__.to_vec(D));
            mu = Eigen::Matrix<double, Eigen::Dynamic, 1>(D);
            vals_r__ = context__.vals_r("mu");
            pos__ = 0;
            size_t mu_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < mu_j_1_max__; ++j_1__) {
                mu(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "mu", mu, 0);
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "S", "int", context__.to_vec());
            S = int(0);
            vals_i__ = context__.vals_i("S");
            pos__ = 0;
            S = vals_i__[pos__++];
            check_greater_or_equal(function__, "S", S, 1);
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "mean_omega", "double", context__.to_vec());
            mean_omega = double(0);
            vals_r__ = context__.vals_r("mean_omega");
            pos__ = 0;
            mean_omega = vals_r__[pos__++];
            check_greater_or_equal(function__, "mean_omega", mean_omega, 0);
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "sd_omega", "double", context__.to_vec());
            sd_omega = double(0);
            vals_r__ = context__.vals_r("sd_omega");
            pos__ = 0;
            sd_omega = vals_r__[pos__++];
            check_greater_or_equal(function__, "sd_omega", sd_omega, 0);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "alpha", "double", context__.to_vec());
            alpha = double(0);
            vals_r__ = context__.vals_r("alpha");
            pos__ = 0;
            alpha = vals_r__[pos__++];
            check_greater_or_equal(function__, "alpha", alpha, 0);
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "ell", "double", context__.to_vec());
            ell = double(0);
            vals_r__ = context__.vals_r("ell");
            pos__ = 0;
            ell = vals_r__[pos__++];
            check_greater_or_equal(function__, "ell", ell, 0);
            current_statement_begin__ = 16;
            context__.validate_dims("data initialization", "nugget", "double", context__.to_vec());
            nugget = double(0);
            vals_r__ = context__.vals_r("nugget");
            pos__ = 0;
            nugget = vals_r__[pos__++];
            check_greater_or_equal(function__, "nugget", nugget, 0);
            current_statement_begin__ = 17;
            context__.validate_dims("data initialization", "c", "int", context__.to_vec());
            c = int(0);
            vals_i__ = context__.vals_i("c");
            pos__ = 0;
            c = vals_i__[pos__++];
            check_greater_or_equal(function__, "c", c, 0);
            // initialize transformed data variables
            current_statement_begin__ = 20;
            validate_non_negative_index("y_reg", "D", D);
            y_reg = Eigen::Matrix<double, Eigen::Dynamic, 1>(D);
            stan::math::fill(y_reg, DUMMY_VAR__);
            current_statement_begin__ = 21;
            validate_non_negative_index("C", "D", D);
            validate_non_negative_index("C", "D", D);
            C = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(D, D);
            stan::math::fill(C, DUMMY_VAR__);
            current_statement_begin__ = 22;
            validate_non_negative_index("L", "D", D);
            validate_non_negative_index("L", "D", D);
            L = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(D, D);
            stan::math::fill(L, DUMMY_VAR__);
            current_statement_begin__ = 23;
            a = double(0);
            stan::math::fill(a, DUMMY_VAR__);
            current_statement_begin__ = 24;
            b = double(0);
            stan::math::fill(b, DUMMY_VAR__);
            current_statement_begin__ = 25;
            validate_non_negative_index("omega", "S", S);
            omega = Eigen::Matrix<double, Eigen::Dynamic, 1>(S);
            stan::math::fill(omega, DUMMY_VAR__);
            current_statement_begin__ = 26;
            validate_non_negative_index("log_omega", "S", S);
            log_omega = Eigen::Matrix<double, Eigen::Dynamic, 1>(S);
            stan::math::fill(log_omega, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 29;
            for (int i = 1; i <= D; ++i) {
                current_statement_begin__ = 30;
                stan::model::assign(y_reg, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            std::max(get_base1(y, i, "y", 1), c), 
                            "assigning variable y_reg");
            }
            current_statement_begin__ = 33;
            stan::math::assign(C, cov_exp_quad(x, 1, ell));
            current_statement_begin__ = 34;
            for (int i = 1; i <= D; ++i) {
                current_statement_begin__ = 34;
                stan::model::assign(C, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            (get_base1(C, i, i, "C", 1) + nugget), 
                            "assigning variable C");
            }
            current_statement_begin__ = 35;
            stan::math::assign(L, cholesky_decompose(C));
            current_statement_begin__ = 37;
            stan::math::assign(b, (mean_omega / pow(sd_omega, 2)));
            current_statement_begin__ = 38;
            stan::math::assign(a, (mean_omega * b));
            current_statement_begin__ = 39;
            stan::model::assign(omega, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        gamma_cdf(1.5, a, b), 
                        "assigning variable omega");
            current_statement_begin__ = 40;
            for (int i = 2; i <= S; ++i) {
                current_statement_begin__ = 40;
                stan::model::assign(omega, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (gamma_cdf((i + 0.5), a, b) - gamma_cdf((i - 0.5), a, b)), 
                            "assigning variable omega");
            }
            current_statement_begin__ = 41;
            stan::math::assign(omega, divide(omega, sum(omega)));
            current_statement_begin__ = 42;
            stan::math::assign(log_omega, stan::math::log(omega));
            // validate transformed data
            current_statement_begin__ = 20;
            check_greater_or_equal(function__, "y_reg", y_reg, 0);
            current_statement_begin__ = 21;
            stan::math::check_cov_matrix(function__, "C", C);
            current_statement_begin__ = 23;
            check_greater_or_equal(function__, "a", a, 0);
            current_statement_begin__ = 24;
            check_greater_or_equal(function__, "b", b, 0);
            current_statement_begin__ = 25;
            stan::math::check_simplex(function__, "omega", omega);
            current_statement_begin__ = 26;
            check_less_or_equal(function__, "log_omega", log_omega, 0);
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 45;
            validate_non_negative_index("epsilon", "D", D);
            num_params_r__ += D;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_lgp_Rt_homo() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 45;
        if (!(context__.contains_r("epsilon")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable epsilon missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("epsilon");
        pos__ = 0U;
        validate_non_negative_index("epsilon", "D", D);
        context__.validate_dims("parameter initialization", "epsilon", "vector_d", context__.to_vec(D));
        Eigen::Matrix<double, Eigen::Dynamic, 1> epsilon(D);
        size_t epsilon_j_1_max__ = D;
        for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
            epsilon(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(epsilon);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable epsilon: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 45;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> epsilon;
            (void) epsilon;  // dummy to suppress unused var warning
            if (jacobian__)
                epsilon = in__.vector_constrain(D, lp__);
            else
                epsilon = in__.vector_constrain(D);
            // transformed parameters
            current_statement_begin__ = 48;
            validate_non_negative_index("f", "D", D);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> f(D);
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 49;
            validate_non_negative_index("R", "D", D);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> R(D);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 50;
            validate_non_negative_index("psi", "D", D);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> psi(D);
            stan::math::initialize(psi, DUMMY_VAR__);
            stan::math::fill(psi, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 52;
            stan::math::assign(f, multiply(multiply(alpha, L), epsilon));
            current_statement_begin__ = 53;
            stan::math::assign(R, stan::math::exp(f));
            current_statement_begin__ = 55;
            stan::math::assign(psi, rep_vector(0, D));
            current_statement_begin__ = 56;
            stan::model::assign(psi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable psi");
            current_statement_begin__ = 57;
            for (int i = 2; i <= D; ++i) {
                current_statement_begin__ = 58;
                if (as_bool(logical_lte(i, S))) {
                    current_statement_begin__ = 59;
                    for (int j = 1; j <= (i - 1); ++j) {
                        current_statement_begin__ = 60;
                        stan::model::assign(psi, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    (get_base1(psi, i, "psi", 1) + ((get_base1(R, (i - j), "R", 1) * get_base1(y_reg, (i - j), "y_reg", 1)) * get_base1(omega, j, "omega", 1))), 
                                    "assigning variable psi");
                    }
                } else {
                    current_statement_begin__ = 63;
                    for (int j = 1; j <= S; ++j) {
                        current_statement_begin__ = 64;
                        stan::model::assign(psi, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    (get_base1(psi, i, "psi", 1) + ((get_base1(R, (i - j), "R", 1) * get_base1(y_reg, (i - j), "y_reg", 1)) * get_base1(omega, j, "omega", 1))), 
                                    "assigning variable psi");
                    }
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 48;
            size_t f_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(f(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: f" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable f: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 49;
            size_t R_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(R(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: R" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable R: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "R", R, 0);
            current_statement_begin__ = 50;
            size_t psi_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(psi(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: psi" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable psi: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "psi", psi, 0);
            // model body
            current_statement_begin__ = 70;
            lp_accum__.add(poisson_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_min_max((D_seed + 1), D), stan::model::nil_index_list()), "y"), add(stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_min_max((D_seed + 1), D), stan::model::nil_index_list()), "mu"), stan::model::rvalue(psi, stan::model::cons_list(stan::model::index_min_max((D_seed + 1), D), stan::model::nil_index_list()), "psi"))));
            current_statement_begin__ = 71;
            lp_accum__.add(std_normal_log<propto__>(epsilon));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("epsilon");
        names__.push_back("f");
        names__.push_back("R");
        names__.push_back("psi");
        names__.push_back("log_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(D);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(D);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(D);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(D);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((D - D_seed));
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_lgp_Rt_homo_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> epsilon = in__.vector_constrain(D);
        size_t epsilon_j_1_max__ = D;
        for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
            vars__.push_back(epsilon(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 48;
            validate_non_negative_index("f", "D", D);
            Eigen::Matrix<double, Eigen::Dynamic, 1> f(D);
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 49;
            validate_non_negative_index("R", "D", D);
            Eigen::Matrix<double, Eigen::Dynamic, 1> R(D);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 50;
            validate_non_negative_index("psi", "D", D);
            Eigen::Matrix<double, Eigen::Dynamic, 1> psi(D);
            stan::math::initialize(psi, DUMMY_VAR__);
            stan::math::fill(psi, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 52;
            stan::math::assign(f, multiply(multiply(alpha, L), epsilon));
            current_statement_begin__ = 53;
            stan::math::assign(R, stan::math::exp(f));
            current_statement_begin__ = 55;
            stan::math::assign(psi, rep_vector(0, D));
            current_statement_begin__ = 56;
            stan::model::assign(psi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable psi");
            current_statement_begin__ = 57;
            for (int i = 2; i <= D; ++i) {
                current_statement_begin__ = 58;
                if (as_bool(logical_lte(i, S))) {
                    current_statement_begin__ = 59;
                    for (int j = 1; j <= (i - 1); ++j) {
                        current_statement_begin__ = 60;
                        stan::model::assign(psi, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    (get_base1(psi, i, "psi", 1) + ((get_base1(R, (i - j), "R", 1) * get_base1(y_reg, (i - j), "y_reg", 1)) * get_base1(omega, j, "omega", 1))), 
                                    "assigning variable psi");
                    }
                } else {
                    current_statement_begin__ = 63;
                    for (int j = 1; j <= S; ++j) {
                        current_statement_begin__ = 64;
                        stan::model::assign(psi, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    (get_base1(psi, i, "psi", 1) + ((get_base1(R, (i - j), "R", 1) * get_base1(y_reg, (i - j), "y_reg", 1)) * get_base1(omega, j, "omega", 1))), 
                                    "assigning variable psi");
                    }
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 49;
            check_greater_or_equal(function__, "R", R, 0);
            current_statement_begin__ = 50;
            check_greater_or_equal(function__, "psi", psi, 0);
            // write transformed parameters
            if (include_tparams__) {
                size_t f_j_1_max__ = D;
                for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                    vars__.push_back(f(j_1__));
                }
                size_t R_j_1_max__ = D;
                for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                    vars__.push_back(R(j_1__));
                }
                size_t psi_j_1_max__ = D;
                for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
                    vars__.push_back(psi(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 74;
            validate_non_negative_index("log_lik", "(D - D_seed)", (D - D_seed));
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik((D - D_seed));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 76;
            for (int i = (D_seed + 1); i <= D; ++i) {
                current_statement_begin__ = 77;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni((i - D_seed)), stan::model::nil_index_list()), 
                            poisson_log(get_base1(y, i, "y", 1), (get_base1(mu, i, "mu", 1) + get_base1(psi, i, "psi", 1))), 
                            "assigning variable log_lik");
            }
            // validate, write generated quantities
            current_statement_begin__ = 74;
            size_t log_lik_j_1_max__ = (D - D_seed);
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_lgp_Rt_homo";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t epsilon_j_1_max__ = D;
        for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "epsilon" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t psi_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "psi" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = (D - D_seed);
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t epsilon_j_1_max__ = D;
        for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "epsilon" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t psi_j_1_max__ = D;
            for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "psi" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = (D - D_seed);
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_lgp_Rt_homo_namespace::model_lgp_Rt_homo stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
